packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: 6.0.3
  eslint: 9.39.5
  prettier: 3.9.9
  eslint-config-prettier: 10.1.8
  '@types/node': 22.20.4

onlyBuiltDependencies:
  - prisma
  - '@prisma/engines'
  - bcrypt

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
